Initial version of languageServerProtocol module
For #1. Implemented yesterday on, where else, a train ride. It already
no longer matches the design I actually want, but I haven’t yet had the
time to put those musings into code, so I’ll add them to the issue and
commit this code as it is for now.

(No automatic tests, but the sendMessage script sends a message with the
right format (Content-Length), and I’ve manually tested that the module
can consume its own reply as request again.)

diff --git a/test b/test
--- a/test
+++ b/test
@@ -18,17 +18,17 @@ function quietly {
 }
 
 function build-jvm {
-    quietly ceylon compile de.lucaswerkmeister.ceylond.{core,recordBased,packetBased,daemonizeProgram} test.de.lucaswerkmeister.ceylond || die 'JVM build error'
+    quietly ceylon compile de.lucaswerkmeister.ceylond.{core,recordBased,packetBased,daemonizeProgram,languageServerProtocol} test.de.lucaswerkmeister.ceylond || die 'JVM build error'
     quietly ceylon fat-jar test.de.lucaswerkmeister.ceylond || die 'JVM jar error'
 }
 function build-js {
-    quietly ceylon compile-js de.lucaswerkmeister.ceylond.{core,recordBased,packetBased,daemonizeProgram} test.de.lucaswerkmeister.ceylond || die 'JS build error'
+    quietly ceylon compile-js de.lucaswerkmeister.ceylond.{core,recordBased,packetBased,daemonizeProgram,languageServerProtocol} test.de.lucaswerkmeister.ceylond || die 'JS build error'
     if [[ -v nocopydeps ]]; then
         deps=()
     else
         deps=(--with-dependencies --include-language)
     fi
-    quietly ceylon copy --js "${deps[@]}" --out node_modules de.lucaswerkmeister.ceylond.{core,recordBased,packetBased,daemonizeProgram} test.de.lucaswerkmeister.ceylond || die 'JS copy error'
+    quietly ceylon copy --js "${deps[@]}" --out node_modules de.lucaswerkmeister.ceylond.{core,recordBased,packetBased,daemonizeProgram,languageServerProtocol} test.de.lucaswerkmeister.ceylond || die 'JS copy error'
 }
 function build {
     for backend in ${backends:-jvm js}; do
